services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - desking-mysql:/var/lib/postgresql/data
    networks:
      - local_app_network

networks:
  local_app_network: {}

volumes:
  desking-mysql: {}
